# BlackRoad OS Stale Bot Configuration
daysUntilStale: 60
daysUntilClose: 14
exemptLabels:
  - pinned
  - security
  - critical
  - in-progress
staleLabel: stale
markComment: |
  🖤 This issue has been automatically marked as stale because it has not had recent activity.

  It will be closed in 14 days if no further activity occurs.

  If this issue is still relevant, please comment or remove the stale label.

  Thank you for contributing to BlackRoad OS!
closeComment: |
  🖤 This issue has been automatically closed due to inactivity.

  Feel free to reopen if the issue persists or you have additional information.

  — BlackRoad OS Team
